version: '3.7'

services:

    winery-mongodb:
        image: mongo
        container_name: winery-mongodb
        ports: 
          - '27017:27017'
        # restart: always
        environment: 
            MONGO_INITDB_DATABASE: smart-dev
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: password
        volumes: 
            - './data:/data'
            - ./init-mongo.js :/docker-entrypoint-initdb.d/

    winery-service:
        build: .
        ports: 
          - 8000:8000
        container_name: winery-service
        restart: always
        volumes: 
          - './app:/app'